// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('TEMAPApp').controller('MainCtrl', [
    '$scope', function($scope) {
      return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
    }
  ]);

}).call(this);
