// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('TEMAPApp').controller('ObjektTypCtrl', function($scope, ObjectType) {
    $scope.objectTypes = [
      {
        id: 0,
        name: 'Belysningsstolpe'
      }, {
        id: 1,
        name: 'Kabelskåp'
      }, {
        id: 2,
        name: 'Nätstation'
      }
    ];
    return $scope.setType = function(type) {
      $scope.objTab.active = true;
      return ObjectType.selected = '' + type.id;
    };
  });

}).call(this);
