// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('TEMAPApp').controller('ObjektCtrl', function($scope, $timeout, ObjectType, data, db, scrollItems) {
    $scope.ObjectType = ObjectType;
    $scope.scrollItems = scrollItems;
    scrollItems.filter = {
      text: ''
    };
    $scope.$on('data::dataUpdated', function() {
      return $scope.$apply();
    });
    $scope.$on('geo::locationUpdate', function(scope, ev) {
      return $scope.$apply(function() {
        return scrollItems.setLocation(ev.coords);
      });
    });
    $scope.selectItem = function(item) {
      $scope.mapTab.disabled = false;
      data.setSelectedItem(item);
      return $timeout(function() {
        $scope.mapTab.active = true;
        return $timeout(function() {
          return $scope.mapTab.updateSize = true;
        });
      });
    };
    $scope.filterArray = function(base) {
      var item, re, result, _i, _len;
      result = [];
      re = new RegExp($scope.scrollItems.filter.text, 'i');
      for (_i = 0, _len = base.length; _i < _len; _i++) {
        item = base[_i];
        if (item.n.match(re)) {
          result.push(item);
        }
      }
      return result;
    };
    $scope.applyTextFilter = function() {
      var base;
      base = scrollItems.getBaseItems().slice(0);
      return scrollItems.setItems($scope.filterArray(base));
    };
    return $scope.toggleGeoSort = function() {
      var items;
      if (scrollItems.toggleGeoSort()) {
        items = scrollItems.getItems();
      } else {
        items = scrollItems.getBaseItems().slice(0);
      }
      return scrollItems.setItems($scope.filterArray(items));
    };
  });

}).call(this);
