// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('TEMAPApp').controller('ObjektCtrl', function($scope, ObjectType, scrollItems) {
    $scope.ObjectType = ObjectType;
    return $scope.scrollItems = scrollItems;
  });

}).call(this);
