// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('TEMAPApp').controller('ObjektTypCtrl', function($scope, ObjectType, scrollItems, data) {
    $scope.objectTypes = [
      {
        id: 'belysning',
        name: 'Belysningsstolpe'
      }, {
        id: 'kabelskap',
        name: 'Kabelskåp'
      }, {
        id: 'natstationer',
        name: 'Nätstation'
      }
    ];
    return $scope.setType = function(type) {
      scrollItems.setBaseItems(data[type.id]);
      scrollItems.filter.text = '';
      if (scrollItems.geoSort) {
        scrollItems.toggleGeoSort(function(sorted) {
          return $scope.$apply(function() {
            return scrollItems.setBaseItems(sorted);
          });
        }, true);
      }
      $scope.objTab.active = true;
      return ObjectType.selected = type.id;
    };
  });

}).call(this);
