// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('TEMAPApp').controller('TabCtrl', function($scope) {
    $scope.typeTab = {
      active: true
    };
    $scope.objTab = {
      active: false
    };
    return $scope.mapTab = {
      active: false
    };
  });

}).call(this);
