// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('TEMAPApp').factory('data', function($rootScope, $http, db) {
    var broadcast, expectedcount, fetch, loadcount, noCache, scope, update;
    scope = null;
    expectedcount = 3;
    loadcount = 0;
    noCache = function() {
      return '?nocache=' + (new Date()).getTime();
    };
    broadcast = function(name) {
      loadcount++;
      if (loadcount === expectedcount) {
        return $rootScope.$broadcast('data::dataUpdated');
      }
    };
    update = function(name, version) {
      return $http.get('data/' + name + '.json' + noCache()).then(function(res) {
        return db.initDb(function() {
          return db.persist(name, version, res.data, function() {
            return fetch(name);
          });
        });
      });
    };
    fetch = function(name) {
      return db.getAsArray(name, function(arr) {
        scope[name] = arr;
        return broadcast(name);
      });
    };
    return {
      update: function() {
        scope = this;
        return $http.get('data/version.json' + noCache()).then(function(res) {
          return db.initDb(function() {
            var k, v, versions;
            versions = res.data;
            for (k in versions) {
              v = versions[k];
              db.needsUpdate(k, v, update, fetch);
            }
            return 1;
          });
        });
      }
    };
  });

}).call(this);
