// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('TEMAPApp').factory('geo', function($rootScope) {
    var locationError, locationUpdate;
    navigator.geolocation.getCurrentPosition;
    locationError = function() {
      return $rootScope.$broadcast('geo::locationUnavailable');
    };
    locationUpdate = function(pos) {
      return $rootScope.$broadcast('geo::locationUpdate', pos);
    };
    return navigator.geolocation.watchPosition(locationUpdate, locationError, {
      enableHighAccuracy: true,
      timeout: 60000,
      maximumAge: 600000
    });
  });

}).call(this);
