// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('TEMAPApp').factory('mergeSort', function() {
    var merge, mergeSort;
    merge = function(prop, left, right) {
      var result;
      result = [];
      while (left.length > 0 && right.length > 0) {
        if (left[0][prop] <= right[0][prop]) {
          result.push(left.shift());
        } else {
          result.push(right.shift());
        }
      }
      while (left.length > 0) {
        result.push(left.shift());
      }
      while (right.length > 0) {
        result.push(right.shift());
      }
      return result;
    };
    mergeSort = function(arr, prop, cb) {
      var cbcount, left, leftCb, middle, right, rightCb, sortedLeft, sortedRight;
      if (arr.length < 2) {
        cb(arr);
        return;
      }
      cbcount = 0;
      middle = Math.floor(arr.length / 2);
      left = arr.slice(0, middle);
      right = arr.slice(middle, arr.length);
      sortedLeft = null;
      sortedRight = null;
      leftCb = function(result) {
        sortedLeft = result;
        if (sortedRight !== null) {
          return cb(merge(prop, sortedLeft, sortedRight));
        }
      };
      rightCb = function(result) {
        sortedRight = result;
        if (sortedLeft !== null) {
          return cb(merge(prop, sortedLeft, sortedRight));
        }
      };
      return setTimeout(function() {
        mergeSort(left, prop, leftCb);
        return mergeSort(right, prop, rightCb);
      }, 0);
    };
    return {
      sort: function(arr, prop, cb) {
        return mergeSort(arr, prop, cb);
      }
    };
  });

}).call(this);
