// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('TEMAPApp').factory('scrollItems', function(mergeSort) {
    var baseItems, end, items, numberItems, start;
    items = [];
    numberItems = 50;
    start = 0;
    end = numberItems;
    baseItems = null;
    return {
      positionUnavailable: true,
      totalSize: 0,
      currentItems: [],
      bottomPadSize: 0,
      topPadSize: 0,
      offset: 0,
      geoSort: false,
      getBaseItems: function() {
        return baseItems;
      },
      executeNameSort: function(cb) {
        var sorted;
        sorted = baseItems.slice(0);
        return mergeSort.sort(sorted, 'n', cb);
      },
      executeGeoSort: function(cb) {
        var sorted;
        sorted = baseItems.slice(0);
        return mergeSort.sort(sorted, 'dist', cb);
      },
      estimateDistance: function() {
        var item, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = baseItems.length; _i < _len; _i++) {
          item = baseItems[_i];
          _results.push(item.dist = (Math.pow(item.la - this.pos.latitude, 2)) + (Math.pow(item.lo - this.pos.longitude, 2)));
        }
        return _results;
      },
      toggleGeoSort: function(cb, state) {
        if (state == null) {
          state = !this.geoSort;
        }
        this.geoSort = state;
        if (this.geoSort) {
          this.estimateDistance();
          return this.executeGeoSort(cb);
        } else {
          return this.executeNameSort(cb);
        }
      },
      setLocation: function(pos) {
        this.positionUnavailable = false;
        return this.pos = pos;
      },
      setItems: function(arr) {
        items = arr;
        end = numberItems;
        this.currentItems = items.slice(0, +end + 1 || 9e9);
        return $(window).scrollTop(0);
      },
      setBaseItems: function(arr) {
        baseItems = arr;
        return this.setItems(baseItems);
      },
      loadMore: function(ev) {
        return this.currentItems = items.slice(0, +(end += numberItems) + 1 || 9e9);
      }
    };
  });

}).call(this);
