// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  var TEMAPApp;

  TEMAPApp = angular.module('TEMAPApp', ['ui.bootstrap', 'infinite-scroll']);

  window.TEMAPApp = TEMAPApp;

  TEMAPApp.factory('ObjectType', function() {
    return {
      selected: null
    };
  });

}).call(this);
