// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  TEMAPApp.directive('autosize', function($window) {
    return function($scope, element, attrs) {
      var elems, resizor, selector, selectors, _i, _len;
      selectors = attrs.autosize.split(',');
      elems = [];
      for (_i = 0, _len = selectors.length; _i < _len; _i++) {
        selector = selectors[_i];
        elems.push($(selector));
      }
      resizor = function() {
        return $scope.$apply(function() {
          var el, height, _j, _len1;
          height = 0;
          for (_j = 0, _len1 = elems.length; _j < _len1; _j++) {
            el = elems[_j];
            if (el.is(':visible')) {
              height += el.outerHeight(true);
            }
          }
          return element.height($window.innerHeight - height);
        });
      };
      angular.element($window).bind('resize', resizor);
      element.bind('$destroy', function() {
        return angular.element($window).unbind('resize', resizor);
      });
      return setTimeout(function() {
        return resizor();
      }, 0);
    };
  });

}).call(this);
